#!/bin/bash

# ////////////////////////////////////////////////////////////
# //////////////////    VARIABELS DEFINITION    //////////////
# ////////////////////////////////////////////////////////////

BoxWhith=70
consol_X=$(tput cols)
consol_Y=$(tput lines)
BoxStartX=$(( ($consol_X - $BoxWhith)/2  ))
BoxStartY=3

working_dir=$(pwd)
input_cascade_index=1
setup_process=true
MAXPAGES=12

LANGUAGE=German
USERNAME=user
USERPASSWORD=user
ROOTACCOUNT=no
ROOTPASSWORD=root
TIMEZONE=Europe
TIMESUBZONE=Berlin
TIMEFORMAT=utc
HOSTNAME=theMashine
DESKTOP=cinnamon
GRAFIKDRIVER=virtualbox

INSTALLMOD=Auto
SWAPSIZE=1024M
HDDNAME=none

# variables for manual munting only
PARTNAME=none
ROOT_MOUNTED="not mounted"
BOOT_MOUNTED="not mounted"
HOME_MOUNTED="not mounted"
SWAP_MOUNTED="not mounted"

#===============================================================================










# ////////////////////////////////////////////////////////////
# //////////////////    INCLUDES			    //////////////
# ////////////////////////////////////////////////////////////

source $working_dir/lib/funktions/harddrive_operations
source $working_dir/lib/funktions/harddrive_operations_normal_manual
source $working_dir/lib/funktions/harddrive_operations_btrfs

source $working_dir/lib/funktions/user_operations
source $working_dir/lib/funktions/languge_operations
source $working_dir/lib/funktions/install_pacages

source $working_dir/lib/input_cascade
source $working_dir/lib/normal_install
#===============================================================================










# ////////////////////////////////////////////////////////////
# //////////////////    INPUT CASKADE	   ///////////////////
# ////////////////////////////////////////////////////////////

function f_input_cascade() {

	while $setup_process ; do
		
		#===== Stay in Range 1 -> MAXPAGES================================================

		if [ "$input_cascade_index" = "$(( $MAXPAGES + 1 ))" ;
			then
  				input_cascade_index=$MAXPAGES
  		
  		elif [ "$input_cascade_index" = "0" ]; 
  			then
  				input_cascade_index=1
  		fi
		#=================================================================================


		clear
		
		case $input_cascade_index in
			1 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Select you language.\n\n"
				echo -e "Actual Language: $LANGUAGE"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetLanguage
  				fi ;;

			2 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Enter you User name.\n\n"
				echo -e "Actual username: $USERNAME"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetUserName
  				fi ;;

			3 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Enter a Password for $USERNAME."
				echo -e "Default Password is: user\n\n"
				echo -e "Aktual password: :) "
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetUserPassword
  				fi ;;

			4 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Do you want to activate the ROOT account?\n\n"
				echo -e "Current Status for ROOT account is: $ROOTACCOUNT"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetRootAccount
  				fi ;;

			5 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Select you time zone.\n\n"
				echo -e "Actual time zone: $TIMEZONE | $TIMESUBZONE | $TIMEFORMAT"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetTimezone
  				fi ;;

			6 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Enter a hostname for this computer.\n\n"
				echo -e "Actual hostname: $HOSTNAME"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetHostname
  				fi ;;

			7 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Select your Desktop.\n\n"
				echo -e "Aktual Desktop: $DESKTOP"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetDesktop
  				fi ;;

			8 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Select your Grafikdriver.\n\n"
				echo -e "Aktual Grafikdriver: $GRAFIKDRIVER"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetGrefikdriver
  				fi ;;

			9 )
				echo -e "Page $input_cascade_index of $MAXPAGES"					
				echo -e "==========================================================="
				echo -e "Select installatin mod.\n\n"
				echo -e "Aktual installation mode: $INSTALLMOD"
				echo -e "==========================================================="
  				echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "e" ];
  					then
    					f_SetInstallmode
  				fi ;;

			10 )
				if [ "$INSTALLMOD" = "manual" ];
					then
    					:
    				else
    					echo -e "Page $input_cascade_index of $MAXPAGES"					
						echo -e "==========================================================="
						echo -e "Select a harddrive for the installation\n\n"
						echo -e "Aktual harddrive: $HDDNAME"
						echo -e "==========================================================="
  						echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
						read -N 1 -rs input_cascade

  						if [ "$input_cascade" = "e" ];
  							then
    							f_generate_harddrive_menu
  						fi
  				fi ;;

			11 )
				if [ "$INSTALLMOD" = "manual" ];
					then
    					:
    				else
    					echo -e "Page $input_cascade_index of $MAXPAGES"
						echo -e "==========================================================="
						echo -e "Select the size of the SWAP.\n\n"
						echo -e "Aktual SWAP size: $SWAPSIZE"
						echo -e "==========================================================="
  						echo -e "(1) Back | (2) Next | (e) Edit |\t\t| (9) End |"
  				
						read -N 1 -rs input_cascade

  						if [ "$input_cascade" = "e" ];
  							then
    							f_set_swap_size
  						fi
  				fi ;;

			12 )
				echo -e "Page $input_cascade_index of $MAXPAGES"
				echo -e "==========================================================="
				echo -e "Summary:"
				echo -e ""
				echo -e "Languge:\t\t$LANGUAGE"
				echo -e "User:\t\t\t$USERNAME"
				echo -e "User password:\t\t$USERPASSWORD"
				echo -e "Activate Root:\t\t$ROOTACCOUNT"
				echo -e "Timezone:\t\t$TIMEZONE | $TIMESUBZONE | $TIMEFORMAT"
				echo -e "Hostname:\t\t$HOSTNAME"
				echo -e "Desktop:\t\t$DESKTOP"
				echo -e "Grefikdriver:\t\t$GRAFIKDRIVER"
				echo -e "Installmode:\t\t$INSTALLMOD"
				
				if [ "$INSTALLMOD" = "manual" ];
					then
    					:
    				else
						echo -e "Harddrive:\t\t$HDDNAME"
						echo -e "SWAP size:\t\t$SWAPSIZE MB\n"
				fi
				
				echo -e "==========================================================="
  				echo -e "(1) Back |\t| (5) Start Installation |\t| (9) Ende |"
  				
				read -N 1 -rs input_cascade

  				if [ "$input_cascade" = "5" ];
  					then
    					f_start_setup
    					break
  				fi ;;

			esac
  		 
  		read -rsn1 input_cascade
		  	
  		if [ "$input_cascade" = "1" ];
  			then
    			input_cascade_index=$(( $input_cascade_index - 1 ))
  		
  		elif [ "$input_cascade" = "2" ];
  			then
    			input_cascade_index=$(( $input_cascade_index + 1 ))
    	
    	elif [ "$input_cascade" = "9" ];
    		then
    			setup_process=false
  		fi
		
  	done
}
#===============================================================================










# START INSTALLATION
#===============================================================================
function f_start_setup() {

	case $INSTALLMOD in

		Auto )
			f_Btrfs_harddrive_preparation
			f_normal_installation ;;

		manual )
			f_manual_partition
			f_normal_installation ;;
	esac
}
#===============================================================================










f_input_cascade

clear
echo -e "==============================================================="
echo -e "PrimeArch was installed\n\n"
echo -e "==============================================================="
echo -e "\t\t\t\t\t\t| (ENTER) End |"

read -p ""