#!/bin/bash

# ////////////////////////////////////////////////////////////
# //////////////////    VARIABELS DEFINITION    //////////////
# ////////////////////////////////////////////////////////////

# set Variabels
BoxWhith=70
consol_X=$(tput cols)
consol_Y=$(tput lines)
BoxStartX=$(( ($consol_X - $BoxWhith)/2  ))
BoxStartY=3

working_dir=$(pwd)
input_cascade=1

LANGUAGE=German
USERNAME=user
USERPASSWORD=user
ROOTACCOUNT=no
ROOTPASSWORD=root
HOSTNAME="theMashine"
DESKTOP=cinnamon
GRAFIKDRIVER=nvidia
INSTALLMOD=btrfs
SWAPSIZE=2048M

# includes
source $working_dir/lib/input_cascade

source $working_dir/lib/btrfs_install
source $working_dir/lib/zfs_install

source $working_dir/lib/funktions/harddrive_operations
source $working_dir/lib/funktions/harddrive_operations_normal_manual
source $working_dir/lib/funktions/harddrive_operations_btrfs
source $working_dir/lib/funktions/harddrive_operations_zfs

source $working_dir/lib/funktions/user_operations
source $working_dir/lib/funktions/install_pacages




# /////////////////////////////////////////////////////////////
# //////////////////    START INSTALATION   ///////////////////
# /////////////////////////////////////////////////////////////

function f_game_master()
	{
		while true; do
			clear

			if [ "$input_cascade" = "12" ]; then
  				input_cascade=11
  			fi

  			if [ "$input_cascade" = "0" ]; then
  				input_cascade=1
  			fi

			case $input_cascade in
				1 )
					echo "==========================================================================="
					echo "Aktual Language: $LANGUAGE"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetLanguage
  					fi
					;;
				2 )
					echo "==========================================================================="
					echo "Aktual username: $USERNAME"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetUserName
  					fi
					;;
				3 )
					echo "==========================================================================="
					echo "Aktual password: :) "
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetUserPassword
  					fi
  					;;
				4 )
					echo "==========================================================================="
					echo "Status ROOT account: $ROOTACCOUNT"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetRootAccount
  					fi
					;;
				5 )
					echo "==========================================================================="
					echo "TIMEZONE: $(</tmp/time_region_out) | $(</tmp/time_subregion_out) | $(</tmp/time_format)"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetTimezone
  					fi
					;;
				6 )
					echo "==========================================================================="
					echo "Aktual hostname: $HOSTNAME"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetHostname
  					fi
					;;
				7 )
					echo "==========================================================================="
					echo "Aktual Desktop: $DESKTOP"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetDesktop
  					fi
					;;
				8 )
					echo "==========================================================================="
					echo "Aktual Grafikdriver: $GRAFIKDRIVER"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetGrefikdriver
  					fi
					;;
				9 )					
					echo "==========================================================================="
					echo "Aktual installation mode: $INSTALLMOD"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_SetInstallmode
  					fi
					;;
				10 )
					echo "==========================================================================="
					echo "Aktual SWAP size: $SWAPSIZE"
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (2) Next | (3) Edit | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "3" ]; then
    					f_set_swap_size
  					fi
					;;
				11 )
					echo "============================================================================"
					echo "Summary:"
					echo ""
					echo -e "Languge:\t\t$LANGUAGE"
					echo -e "User:\t\t\t$USERNAME"
					echo -e "User password:\t\t$USERPASSWORD"
					echo -e "Activate Root:\t\t$ROOTACCOUNT"
					echo -e "Timezone:\t\t$(</tmp/time_region_out) | $(</tmp/time_subregion_out) | $(</tmp/time_format)"
					echo -e "Hostname:\t\t$HOSTNAME"
					echo -e "Desktop:\t\t$DESKTOP"
					echo -e "Grefikdriver:\t\t$GRAFIKDRIVER"
					echo -e "Installmode:\t\t$INSTALLMOD"
					echo -e "SWAP size:\t\t$SWAPSIZE MB" 
					echo -e '\n\n'
					echo "==========================================================================="
  					echo "(1) Back | (5) Start Installation | (9) Ende | Page $input_cascade of 11"
  					read -rsn1 input

  					if [ "$input" = "5" ]; then
    					f_start_setup
    					input_cascade=20
  					fi
					;;
				20 )
					#===============================================================================
					echo "==========================================================================="
					echo -e "Setup is done.\nPlease restart the computer"
					echo -e '\n'
					echo "==========================================================================="
					read -p "(ENTER) End setup |"
					
					exit  ;;
			esac
  			
 
  			read -rsn input
  			
  			if [ "$input" = "1" ]; then
    			input_cascade=$(( $input_cascade - 1 ))
  			elif [ "$input" = "2" ]; then
    			input_cascade=$(( $input_cascade + 1 ))
    		elif [ "$input" = "9" ]; then
    			exit
  			fi
  		done
	}
	

# START INSTALLATION
#===============================================================================
function f_start_setup() 
	{
		case $INSTALLMOD in
			manual )
				f_manual_partition
				f_normal_installation ;;
			zfs )
				f_zfs_harddrive_preparation
				f_zfs_installation ;;
			btrfs )
				f_Btrfs_harddrive_preparation
				f_btrfs_installation ;;
		esac
	}
#===============================================================================

f_game_master