#!/bin/bash

# ////////////////////////////////////////////////////////////
# //////////////////    VARIABELS DEFINITION    //////////////
# ////////////////////////////////////////////////////////////

# set Variabels
BoxWhith=70
consol_X=$(tput cols)
consol_Y=$(tput lines)
BoxStartX=$(( ($consol_X - $BoxWhith)/2  ))
BoxStartY=3

working_dir=$(pwd)
input_cascade_index=1
setup_process=true
MAXPAGES=12

LANGUAGE=German
USERNAME=user
USERPASSWORD=user
ROOTACCOUNT=no
ROOTPASSWORD=root
TIMEZONE=Europe
TIMESUBZONE=Berlin
TIMEFORMAT=utc
HOSTNAME=theMashine
DESKTOP=cinnamon
GRAFIKDRIVER=virtualbox
INSTALLMOD=btrfs
SWAPSIZE=2048M
HDDNAME=none

# includes
source $working_dir/lib/input_cascade

source $working_dir/lib/btrfs_install
source $working_dir/lib/zfs_install

source $working_dir/lib/funktions/harddrive_operations
source $working_dir/lib/funktions/harddrive_operations_normal_manual
source $working_dir/lib/funktions/harddrive_operations_btrfs
source $working_dir/lib/funktions/harddrive_operations_zfs

source $working_dir/lib/funktions/user_operations
source $working_dir/lib/funktions/install_pacages




# /////////////////////////////////////////////////////////////
# //////////////////    START INSTALATION   ///////////////////
# /////////////////////////////////////////////////////////////

function f_game_master() {
	while $setup_process; do
		
		clear

		if [ "$input_cascade_index" = "$( (( MAXPAGES + 1 )) )" ]; then
  			input_cascade_index=$$MAXPAGES
  		fi

  		if [ "$input_cascade_index" = "0" ]; then
  			input_cascade_index=1
  		fi

		case $input_cascade_index in
			1 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo -e "===========================================================================\n"
				echo -e "Select you language.\n"
				echo "Actual Language: $LANGUAGE"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetLanguage
  				fi
				;;
			2 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo -e "===========================================================================\n"
				echo -e "Enter you User name.\n"
				echo "Aktual username: $USERNAME"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetUserName
  				fi
				;;
			3 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo -e "===========================================================================\n"
				echo -e "Enter a Password for $USERNAME.\nDefault Password is: user.\n"
				echo "Aktual password: :) "
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetUserPassword
  				fi
  				;;
			4 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo -e "===========================================================================\n"
				echo -e "Do you want to activate the ROOT account?\n"
				echo "Status ROOT account: $ROOTACCOUNT"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetRootAccount
  				fi
				;;
			5 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo -e "===========================================================================\n"
				echo -e "Select you time zone.\n"
				echo "Actual time zone: $TIMEZONE | $TIMESUBZONE | $TIMEFORMAT"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetTimezone
  				fi
				;;
			6 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo "==========================================================================="
				echo "Aktual hostname: $HOSTNAME"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetHostname
  				fi
				;;
			7 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo "==========================================================================="
				echo "Aktual Desktop: $DESKTOP"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetDesktop
  				fi
				;;
			8 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo "==========================================================================="
				echo "Aktual Grafikdriver: $GRAFIKDRIVER"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetGrefikdriver
  				fi
				;;
			9 )
				echo "Page $input_cascade_index of $MAXPAGES"					
				echo "==========================================================================="
				echo "Aktual installation mode: $INSTALLMOD"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetInstallmode
  				fi
				;;
			10 )
				echo "Page $input_cascade_index of $MAXPAGES"					
				echo "==========================================================================="
				echo "Select a harddrive for the installation"
				echo "Aktual harddrive: $HDDNAME"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_SetHarddrive
  				fi
				;;
			11 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo "==========================================================================="
				echo "Aktual SWAP size: $SWAPSIZE"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (2) Next | (e) Edit | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "e" ]; then
    				f_set_swap_size
  				fi
				;;
			12 )
				echo "Page $input_cascade_index of $MAXPAGES"
				echo "============================================================================"
				echo "Summary:"
				echo ""
				echo -e "Languge:\t\t$LANGUAGE"
				echo -e "User:\t\t\t$USERNAME"
				echo -e "User password:\t\t$USERPASSWORD"
				echo -e "Activate Root:\t\t$ROOTACCOUNT"
				echo -e "Timezone:\t\t$TIMEZONE | $TIMESUBZONE | $TIMEFORMAT"
				echo -e "Hostname:\t\t$HOSTNAME"
				echo -e "Desktop:\t\t$DESKTOP"
				echo -e "Grefikdriver:\t\t$GRAFIKDRIVER"
				echo -e "Installmode:\t\t$INSTALLMOD"
				echo -e "Harddrive:\t\t$HDDNAME"
				echo -e "SWAP size:\t\t$SWAPSIZE MB"
				echo -e '\n\n'
				echo "==========================================================================="
  				echo "(1) Back | (5) Start Installation | (9) Ende |"
  				read -rsn1 input

  				if [ "$input" = "5" ]; then
    				f_start_setup
    				input_cascade_index=20
  				fi
				;;
			20 )
				echo "==========================================================================="
				echo -e "Setup is done.\n\nPlease restart the computer"
				echo -e '\n'
				echo "==========================================================================="
				read -p "(ENTER) End setup |"
					
				exit
				#setup_process=false 
				;;
		esac
  			
 
  		read -rsn input
  			
  		if [ "$input" = "1" ]; then
    		input_cascade_index=$(( $input_cascade_index - 1 ))
  		elif [ "$input" = "2" ]; then
    		input_cascade_index=$(( $input_cascade_index + 1 ))
    	elif [ "$input" = "9" ]; then
    		exit
  		fi
  	done
}
	

# START INSTALLATION
#===============================================================================
function f_start_setup() {
	case $INSTALLMOD in
		manual )
			f_manual_partition
			f_normal_installation ;;
		
		zfs )
			f_zfs_harddrive_preparation
			f_zfs_installation ;;
		
		btrfs )
			f_Btrfs_harddrive_preparation
			f_btrfs_installation ;;
	esac
}
#===============================================================================

f_game_master