#!/bin/bash

# set Variabels
terminal_x=$(tput cols)
terminal_y=$(tput lines)

working_dir=$(pwd)
i=0

function f_fill_framebuffer() {

	# generate "line lists" == to terminal_y-1
	for (( i = 0; i < $terminal_y-1; i++ )); do
		# fill generated  "line lists" == up to terminal_x-1
		for (( j = 0; j < $terminal_x-1; j++ )); do
			declare -a framebuffer_line[j]=2
		done
	
	done
}

f_fill_framebuffer

echo -n ${framebuffer_line[*]}


for (( j = 0; j < $terminal_x-1; j++ )); do
    :
done














#framebuffer_line=()
#function f_fill_framebuffer() {
	#for (( i = 0; i < $terminal_y-1; i++ )); do
		#framebuffer_line[i]="$(for (( j = 0; j < $terminal_x-1; j++ )); do
									#echo -n "_"
								#done )"
	#done
#}
























#function f_print_framebuffer() {
	#for (( j = 0; j < $terminal_x; j++ )); do
	#done
#}






#for (( j = 0; j < $terminal_x; j++ )); do
			#framebuffer[i]="a: $j"
		#done