#!/bin/bash

function f_SetLanguage()
	{
		clear
		
		echo "============================================================================"
		echo -e "Please Select You language by entering the coresponding number\n"
		echo "1. German"
		echo "2. English"
		echo "3. Russian"
		echo -e '\n'
		echo "==========================================================================="
  		read -rsn1 input_4

  		if [ "$input_4" = "1" ]; then
    			LANGUAGE=german
  			elif [ "$input_4" = "2" ]; then
    			LANGUAGE=english
  			elif [ "$input_4" = "3" ]; then
    			LANGUAGE=russian
  		fi
  	}


function f_SetUserName()
	{
		clear
		
		echo "============================================================================"
		echo "Please enter username."
		echo -n "Name: " ; read USERNAME
	}


function f_SetUserPassword()
	{
		clear
		
		echo "============================================================================"
		echo "Please enter the password for $USERNAME."
		echo -n "Password: " ; read USERPASSWORD
	}


function f_SetRootAccount()
	{
		clear
	
		echo "============================================================================"
		echo "Activate root Account?"
		echo ""
		echo "1. no"
		echo "2. yes"

		read -rsn1 input_5

  		if [ "$input_5" = "1" ]; then
    			ROOTACCOUNT=no
  		elif [ "$input_5" = "2" ]; then
    			ROOTACCOUNT=yes
  		fi

  		case $ROOTACCOUNT in
  			yes )
				clear
		
				echo "============================================================================"
				echo "Please enter the root password"
				echo -n "Password: " ; read ROOTPASSWORD
				;;
			no )
  				: ;;
  		esac

	}

function f_SetTimezone()
	{
		clear
		
		echo "============================================================================"
		
	}


function f_SetHostname()
	{
		clear
		
		echo "============================================================================"
		echo "Please enter the Hostname."
		echo -n "Name: " ; read HOSTNAME
		
	}


function f_SetDesktop()
	{
		clear
		
		echo "============================================================================"
		echo "Please Select You Desktop by entering the coresponding number"
		echo ""
		echo "1. i3"
		echo "2. Cinnamon"
		echo "3. Gnome"
		echo "4. XFce"
		echo "5. Mate"
		echo "6. No Desktop"
		echo -e '\n'
		echo -n "Desktop: " ; 

		read -rsn1 input_1

  		if [ "$input_1" = "1" ]; then
    		DESKTOP=i3
  		elif [ "$input_1" = "2" ]; then
    		DESKTOP=cinnamon
  		elif [ "$input_1" = "3" ]; then
    		DESKTOP=gnome
    	elif [ "$input_1" = "4" ]; then
    		DESKTOP=xfce
    	elif [ "$input_1" = "5" ]; then
    		DESKTOP=mate
    	elif [ "$input_1" = "6" ]; then
    		DESKTOP=nodesktop
  		fi
	}


function f_SetGrefikdriver()
	{
		clear
		
		echo "============================================================================"
		echo "Please Select You Grafikdriver by entering the coresponding number"
		echo ""
		echo "1. VirtualBox"
		echo "2. Nvidia"
		echo "3. Nouveau"
		echo "4. Ati"
		echo "5. Intel"
		echo "6. No Grafik"
			
		read -rsn1 input_2

  		if [ "$input_2" = "1" ]; then
    		GRAFIKDRIVER=virtualbox
  		elif [ "$input_2" = "2" ]; then
    		GRAFIKDRIVER=nvidia
  		elif [ "$input_2" = "3" ]; then
    		GRAFIKDRIVER=nouveau
    	elif [ "$input_2" = "4" ]; then
    		GRAFIKDRIVER=ati
    	elif [ "$input_2" = "5" ]; then
    		GRAFIKDRIVER=intel
    	elif [ "$input_2" = "6" ]; then
    		GRAFIKDRIVER=nografik
  		fi
	}



function f_SetInstallmode()
	{
		clear
		
		echo "============================================================================"
		echo "Please Select You Instalation mod by entering the coresponding number"
		echo ""
		echo "1. Normal"
		echo "2. Root on ZFS"
		echo "3. Btrfs"
		echo "3. Manual"
		
		read -rsn1 input_3

  		if [ "$input_3" = "1" ]; then
    			INSTALLMOD=normal
  			elif [ "$input_3" = "2" ]; then
    			INSTALLMOD=zfs
  			elif [ "$input_3" = "3" ]; then
    			INSTALLMOD=btrfs
    		elif [ "$input_3" = "4" ]; then
    			INSTALLMOD=manual
    	fi
	}
