#!/bin/bash

function f_wipe_harddrive()
	{
		wipefs -af 	/dev/$(</tmp/hdd_name)
		sgdisk -Z 	/dev/$(</tmp/hdd_name)
		sgdisk -g 	/dev/$(</tmp/hdd_name)
		sgdisk -o 	/dev/$(</tmp/hdd_name)
	}


function f_make_boot_part()
	{
		if [[ -d "/sys/firmware/efi/efivars" ]];
			then
				sgdisk -n 1:0:+256M -c 1:"EFI" 	-t 1:ef00 /dev/$(</tmp/hdd_name)
				mkfs.fat -F32 /dev/$(</tmp/hdd_name)1
			else
				sgdisk -n 1:0:+5M 	-c 1:"BIOS" -t 1:ef02 /dev/$(</tmp/hdd_name)
		fi
	}

function f_make_root_part()
	{
		sgdisk -n 3:0:0 -c 3:"ROOT" -t 3:8300 /dev/$(</tmp/hdd_name)
	}

function f_make_swap() 
	{
		sgdisk -n 2:0:+$SWAPSIZE -c 2:"SWAP" -t 2:8200 /dev/$(</tmp/hdd_name)
		mkswap /dev/$(</tmp/hdd_name)2
	}





################################################################################
######	DYNAMIC MENU GENERATION funktions	####################################
################################################################################

function f_generate_harddrive_menu() {

	#Prepare Disklist
	lsblk -o NAME,SIZE,MODEL,TYPE | grep disk > /tmp/hdlist

	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "HDD Auswahl" \
	--menu "Shoose the harddrive for the installation" 15 $BoxWhith 7 \
		$(awk ' { print $1"\t"$2 } ' < /tmp/hdlist) \
		2>/tmp/hdd_name
}



function f_generate_partition_menu() {

	#Prepare Partitionlist
	lsblk -l -o NAME,SIZE,MODEL,TYPE | grep part > /tmp/partlist

	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "Shoose the partition" \
	--menu "Shoose the partition for "$1 15 $BoxWhith 7 \
		$(awk ' { print $1"\t"$2 } ' < /tmp/partlist) \
		2>/tmp/part_name
}
#===============================================================================
