#!/bin/bash

################################################################################
######	Btrfs partition funktions	################################################
################################################################################

function f_Btrfs_harddrive_preparation(){

	# Generate HDD selection menu
	#===============================================================================
	f_generate_harddrive_menu
				
	f_wipe_harddrive
	
	f_make_boot_part
	f_make_swap
	f_make_root_part
	

	mkfs.btrfs -f /dev/$(</tmp/hdd_name)3
	mkswap /dev/$(</tmp/hdd_name)2

	
	mount /dev/$(</tmp/hdd_name)3 /mnt
	cd /mnt
	btrfs subvolume create ROOT
	btrfs subvolume create home
	btrfs subvolume create snapshots
	btrfs subvolume create pkg
	btrfs subvolume create var
	btrfs subvolume create tmp
	cd ..
	umount /mnt




	mount -o rw,defaults,noatime,compress=lzo,subvol=ROOT /dev/$(</tmp/hdd_name)3 /mnt
	
	if [[ -d "/sys/firmware/efi/efivars" ]];
		then
			mkdir -p /mnt/boot/efi
			mount /dev/$(</tmp/hdd_name)1 /mnt/boot/efi
		else
			:
	fi

	mkdir /mnt/home
	mkdir /mnt/.snapshots
	mkdir -p /mnt/var/cache/pacman/pkg
	mkdir /mnt/tmp
	swapon /dev/$(</tmp/hdd_name)2
	
	mount -o rw,defaults,noatime,compress=lzo,subvol=home /dev/$(</tmp/hdd_name)3 /mnt/home
	mount -o rw,defaults,noatime,compress=lzo,subvol=snapshots /dev/$(</tmp/hdd_name)3 /mnt/.snapshots
	mount -o rw,defaults,noatime,compress=lzo,subvol=pkg /dev/$(</tmp/hdd_name)3 /mnt/var/cache/pacman/pkg
	mount -o rw,defaults,noatime,compress=lzo,subvol=tmp /dev/$(</tmp/hdd_name)3 /mnt/tmp
}