#!/bin/bash

################################################################################
######	Manual partition funktions	############################################
################################################################################

# MANUAL PARTITIONING
function f_manual_partition() {
	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "Manual Partitionig" \
	--menu "" 11 $BoxWhith 4 \
		1 "Partition a harddrive" \
		2 "Mount Partitions" \
		3 "Set SWAP size" \
		4 "Done!" \
		2>/tmp/main_man_part

	case $(</tmp/main_man_part) in
		1 )
			f_generate_harddrive_menu

			f_show_info_for_partition

			cgdisk /dev/$(</tmp/hdd_name)

			# Back to main menu
			f_manual_partition ;;

		2 )
			# Mount ROOT
			case $(</tmp/root_mount)  in
				ok )
					;;
				* )
					f_mount_root ;;
			esac

			# Mount BOOT
			if [[ -d "/sys/firmware/efi/efivars" ]];
				then
					case $(</tmp/boot_mount)  in
						ok )
							;;
						* )
							f_mount_boot ;;
					esac
				else
					:
			fi

			# Mount HOME
			case $(</tmp/home_mount)  in
				ok )
					;;
				* )
					dialog \
					--backtitle 'PrimeArch Installer' \
					--begin $BoxStartY $BoxStartX \
					--title "HOME" \
					--yesno '\n Do you want to mount a HOME partition?' 7 $BoxWhith \

					if [[ $? -eq 0 ]];
						then
							f_mount_home
						else
							echo 'ok' >> /tmp/boot_mount
							break
					fi
			esac

			# Back to main menu
			f_manual_partition ;;

		3 )
			# SWAP size dialog
			#===============================================================================
			dialog \
			--backtitle "PrimeArch Installer" \
			--begin $BoxStartY $BoxStartX \
			--title "SWAP" \
			--inputbox '\nSWAP partition size (in MB)' 9 $BoxWhith \
				2>/tmp/swap_size
			
			# Back to main menu
			f_manual_partition ;;

		4 )
			;;
	esac
}



function f_mount_boot() {
	f_generate_partition_menu BOOT
	
	mkfs.fat -F32 /dev/$(</tmp/part_name)
	mkdir /mnt/boot
	mkdir /mnt/boot/efi
	mount /dev/$(</tmp/part_name) /mnt/boot/efi
	echo 'ok' >> /tmp/boot_mount
}



function f_mount_root() {
	f_generate_partition_menu ROOT
	
	mkfs.ext4 /dev/$(</tmp/part_name)
	mount -t ext4 -o defaults,noatime,discard /dev/$(</tmp/part_name) /mnt
	echo 'ok' >> /tmp/root_mount
}



function f_mount_home() {
	f_generate_partition_menu HOME

	dialog \
	--backtitle 'PrimeArch Installer' \
	--title 'Formating' \
	--begin $BoxStartY $BoxStartX \
	--yesno '\nDo you want to format the HOME partition?' 7 $BoxWhith \

	if [[ $? -eq 0 ]];
		then
			mkfs.ext4 /dev/$(</tmp/part_name)
		else
			break
	fi

	mkdir /mnt/home
	mount -t ext4 -o defaults,noatime,discard /dev/$(</tmp/part_name) /mnt/home
	echo 'ok' >> /tmp/home_mount
}



function f_show_info_for_partition() {
	# Show Partitioning info depending on boot mode
	if [[ -d "/sys/firmware/efi/efivars" ]];
		then
			dialog \
			--backtitle 'PrimeArch Installer' \
			--title 'Partition Table' \
			--begin $BoxStartY $BoxStartX \
			--msgbox '
			Please make shure you make folowing partitions:
			1. EFI ca. 100-256 Mb ( code: ef00 )
	
			if you want an extra HOME partition
			2. ROOT ca. 20-40 Gb ( code: 8300 )
			3. HOME rest of the harddrive ( code: 8300 )

			otherwise you can give the rest of the memory
			to the ROOT partition

			a SWAP partition is not needet, the script will
			setup a SWAP file.' 20 $BoxWhith

		else
			dialog \
			--backtitle 'PrimeArch Installer' \
			--title 'Partition Table' \
			--begin $BoxStartY $BoxStartX \
			--msgbox '
			Please make shure you make folowing partitions:
			1. BOOT ca. 5 Mb ( code: ef02)

			if you want an extra HOME partition
			2. ROOT ca. 20-40 Gb ( code: 8300 )
			3. HOME rest of the harddrive ( code: 8300 )

			otherwise you can give the rest of the memory
			to the ROOT partition

			a SWAP partition is not needet, the script will
			setup a SWAP file.' 20 $BoxWhith
	fi
}
