#!/bin/bash

################################################################################
######	Manual partition funktions	############################################
################################################################################

# MANUAL PARTITIONING
function f_manual_partition() {

	clear
	
	echo -e "==========================================================="
	echo -e "1. Partition a harddrive"
	echo -e "2. Mount partitions"
	echo -e "\t\t\t ROOT: $ROOT_MOUNTED"
	echo -e "\t\t\t BOOT: $BOOT_MOUNTED"
	echo -e "\t\t\t HOME: $HOME_MOUNTED"
	echo -e "\t\t\t SWAP: $SWAP_MOUNTED"
	echo -e "3. Start setup"
	echo -e "==========================================================="
  	echo -e "\t\t\t\t\t\t| (9) End |"
  				
	read -rsn1 input_man_hdd

  	if [ "$input_man_hdd" = "9" ]; then
	   	exit
  	fi




	case $input_man_hdd in
		1 )
			f_generate_harddrive_menu

			f_show_info_for_partition

			cgdisk /dev/$HDDNAME

			# Back to main menu
			f_manual_partition ;;

		2 )
			# Mount ROOT
			case $ROOT_MOUNTED in
				ok )
					;;
				* )
					f_mount_root ;;
			esac

			# Mount BOOT
			if [[ -d "/sys/firmware/efi/efivars" ]];
				then
					case $BOOT_MOUNTED in
						ok )
							;;
						* )
							f_mount_boot ;;
					esac
				else
					:
			fi

			# Mount HOME
			case $HOME_MOUNTED in
				ok )
					;;
				* )
					echo -e "==========================================================="
					echo -e "Do you want to mount an extra HOME partition?\n"
					echo -e "1. Yes"
					echo -e "2. No"

					read -rsn1 input_home

					if [[ "$input_home" = "1" ]];
						then
							f_mount_home
						else
							HOME_MOUNTED="ok"
							:
					fi
			esac

			# Mount SWAP
			case $SWAP_MOUNTED in
				ok )
					;;
				* )
					f_mount_swap ;;
			esac

			
			
			
			# Back to main menu
			f_manual_partition ;;

		3 )
			;;
	esac
}



function f_mount_boot() {
	f_generate_partition_menu BOOT
	
	mkfs.fat -F32 /dev/$PARTNAME
	mkdir -p /mnt/boot/efi
	mount /dev/$PARTNAME /mnt/boot/efi
	BOOT_MOUNTED="ok"
}



function f_mount_root() {
	f_generate_partition_menu ROOT
	
	mkfs.ext4 /dev/$PARTNAME
	mount -t ext4 -o defaults,noatime,discard /dev/$PARTNAME /mnt
	ROOT_MOUNTED="ok"
}



function f_mount_home() {
	f_generate_partition_menu HOME

	echo -e "==========================================================="
	echo -e "Do you want to format the HOME partition?\n"
	echo -e "1. Yes"
	echo -e "2. No"

	read -rsn1 input_format_home
	
	if [[ "$input_format_home" = "1" ]];
		then
			mkfs.ext4 /dev/$PARTNAME
		else
			break
	fi

	mkdir /mnt/home
	mount -t ext4 -o defaults,noatime,discard /dev/$PARTNAME /mnt/home
	HOME_MOUNTED="ok"
}



function f_mount_swap() {
	f_generate_partition_menu SWAP

	swapon /dev/$PARTNAME

	SWAP_MOUNTED="ok"
}



function f_show_info_for_partition() {
	# Show Partitioning info depending on boot mode
	if [[ -d "/sys/firmware/efi/efivars" ]];
		then
			clear
			echo -e "==========================================================="
			echo -e "
Please make shure you make folowing partitions:
1. EFI ca. 100-256 Mb ( code: ef00 )
2. SWAP At yor shoise ( code: 8200 )
	
if you want an extra HOME partition
3. ROOT ca. 20-40 Gb ( code: 8300 )
4. HOME rest of the harddrive ( code: 8300 )

otherwise you can give the rest of the memory
to the ROOT partition\n\n"

			read -p "Press ENTER to to start cgdisk"

		else
			clear
			echo -e "==========================================================="
			echo -e "
Please make shure you make folowing partitions:
1. BOOT ca. 5 Mb ( code: ef02)
2. SWAP At yor shoise ( code: 8200 )

if you want an extra HOME partition
2. ROOT ca. 20-40 Gb ( code: 8300 )
3. HOME rest of the harddrive ( code: 8300 )

otherwise you can give the rest of the memory
to the ROOT partition.\n\n"

			read -p "Press ENTER to to start cgdisk"
	fi
}
