#!/bin/bash


################################################################################
######	SWAP File funktions	####################################################
################################################################################

function f_make_swap_file() {
	
	dd if=/dev/zero of=/mnt/SWAP bs=1M count=$(</tmp/swap_size) status=progress
	mkswap /mnt/SWAP
	chmod 600 /mnt/SWAP

	echo '# SWAP FILE' >> /mnt/etc/fstab
	echo '/SWAP			none      	swap      	defaults  	0 0' >> /mnt/etc/fstab
}

################################################################################
######	DYNAMIC MENU GENERATION funktions	####################################
################################################################################

function f_generate_harddrive_menu() {

	#Prepare Disklist
	lsblk -o NAME,SIZE,MODEL,TYPE | grep disk > /tmp/hdlist

	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "HDD Auswahl" \
	--menu "Shoose the harddrive for the installation" 15 $BoxWhith 7 \
		$(awk ' { print $1"\t"$2 } ' < /tmp/hdlist) \
		2>/tmp/hdd_name
}



function f_generate_partition_menu() {

	#Prepare Partitionlist
	lsblk -l -o NAME,SIZE,MODEL,TYPE | grep part > /tmp/partlist

	dialog \
	--backtitle "PrimeArch" \
	--begin $BoxStartY $BoxStartX \
	--title "Shoose the partition" \
	--menu "Shoose the partition for "$1 15 $BoxWhith 7 \
		$(awk ' { print $1"\t"$2 } ' < /tmp/partlist) \
		2>/tmp/part_name
}
#===============================================================================
