#!/bin/bash

# Pacage installation
#===============================================================================

function f_pakage_install() {
	
	pacstrap /mnt $(awk '{ if($1 !~ /#/) print }' < $working_dir/lib/pakages/$1)
}
#===============================================================================










# Desktops installation
#===============================================================================

function f_install_desktop() {
	f_pakage_install $1
}

function f_install_i3_cosmetics() {

	rm -R /mnt/home/$USERNAME/.config/i3
	git clone https://github.com/dikiy4eburator/i3-config.git /mnt/home/$USERNAME/.config/i3
	arch-chroot /mnt /bin/bash -c "sudo -u $USERNAME yaourt -S --noconfirm polybar-git"
}
#===============================================================================












# YAOURT FUNKTIONS
#===============================================================================

function f_install_trizen() {

	mv $working_dir/lib/funktions/trizen.sh /mnt/home/$USERNAME/trizen.sh
	arch-chroot /mnt /bin/bash -c "sudo -u $USERNAME sh /home/$USERNAME/trizen.sh"
	rm /mnt/home/$USERNAME/trizen.sh
}



function f_install_aur_cosmetiks() {

	while read line
		do
			if [[ `expr "$line" : ".*[!@#\$%^\&*()_+].*"` -gt 0 ]];
				then
					:
				else
					arch-chroot /mnt /bin/bash -c "sudo -u $USERNAME trizen -S --noconfirm $line"
			fi
	done < $working_dir/lib/pakages/pakages_aur
}
#===============================================================================
