#!/bin/bash

# GENERATE AND WRITE ROOT PW
#===============================================================================
function f_set_root_pw() {

	# remove root from shadow file
	awk '{ if($1 !~ /root/) print }' /mnt/etc/shadow > /mnt/etc/new_shadow

	# generate and add root pasword to the new shadow file
	openssl passwd -1 -salt xyz  $ROOTPASSWORD > /tmp/root_pw
	echo "root:$(</tmp/root_pw):17393::::::" >> /mnt/etc/new_shadow
	rm /tmp/root_pw

	# replace shadow with new shadow file
	mv /mnt/etc/new_shadow /mnt/etc/shadow
}
#===============================================================================





# CREATE NEW USER
#===============================================================================
function f_create_new_user() {

	arch-chroot /mnt /bin/bash -c "useradd -m -g users -G wheel,storage,power,network,video,audio -s /usr/bin/fish '$USERNAME'"

	f_set_user_pw

	echo "%wheel ALL=(ALL) ALL" >> /mnt/etc/sudoers.back
}
#===============================================================================





# GENERATE AND WRITE USER PW
#===============================================================================
function f_set_user_pw() {

	# Clear User Password
	awk '{ if($1 !~ /'$USERNAME'/) print }' /mnt/etc/shadow > /mnt/etc/new_shadow

	# Set new User Password
	openssl passwd -1 -salt xyz  $USERPASSWORD > /tmp/user_pw
	echo "$USERNAME:$(</tmp/user_pw):17393:0:99999:7:::" >> /mnt/etc/new_shadow
	rm /tmp/user_pw

	# replace shadow with new shadow file
	mv /mnt/etc/new_shadow /mnt/etc/shadow
}
#===============================================================================